### ISSUE TITLE
Setup course automatic naming convention

### ISSUE THREAD

**Issue by n-meyer** [oel-mediateam/storybook-packager-public#12]
I am working on a meet the instructor SB+ lesson. The setup program is meet the instructor and the setup course is stevens-point. The packager automatically adds an _r to the end of stevens-point in the XML though. Since the SVG is named stevens-point the splash won't show up. This kind of media doesn't really work on the same revision schedule though.
![Screen Shot 2019-05-06 at 12 35 37 PM](https://user-images.githubusercontent.com/49766744/57243486-e15db500-6ffb-11e9-9b7f-eecbc1894f95.png)

**Comment by Lin87** [comment]
Question. Did you leave the revision year field empty?

**Comment by n-meyer** [comment]
Yep, I did. I just did a test with a new project and it seems that by default the _r gets added to the end if you leave the year field blank?

**Comment by Lin87** [comment]
Got it! Found the issue. Working on a fix now.

**Comment by n-meyer** [comment]
Awesome, thanks!

**Comment by Lin87** [comment]
Fixed. Will be in next update.
