### ISSUE TITLE
Sanitize and Format time entry in the Bundle Editor

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/storybook-packager-public#22]
Make sure that if I enter 90 seconds, the field gets formatted as 01:30.

If I enter 00:002312313244, either round to the nearest second or make it zero. whatever is easiest.

Test out other random entries too. Like non-numeric symbols etc.

As it stands now, I can get myself in a situation where I can't fix my incorrect entries.

**Comment by Lin87** [comment]
Updated and to be released in build 24.

Timecode is now sanitized and formatted to either one of the formats: `00:00` or `00:00:00`. However, the seconds can be more than 2 digits. For example, `00:120` will be autocorrected to `02:00`, and `00:00214657892123` will be autocorrected to `00:000`.

Only digits and colons (:) are allowed. All other characters are rejected with an alert.
