### ISSUE TITLE
[Crash] When numbering bundles, if you number them 00:02, 00:06, 00:00 and try to edit '00:00' the application crashes

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/storybook-packager-public#25]
I have a crash that happened when I numbered three different bundle entries 00:04, 00:06, 00:00. When I tried to edit the third time by changing the time in the list I got a crash after double clicking 00:00.

[crash_log.txt](https://github.com/oel-mediateam/storybook-packager-public/files/3287637/crash_log.txt)

**Comment by Lin87** [comment]
Fixed. To be released in build 24. Prevent the first frame from edit and preventing duplicate time resolved this crash.
