### ISSUE TITLE
Multiple Select does not work when adding images to a bundle.

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/storybook-packager-public#26]
I can not select multiple images at the same time in the Open/Save dialog when adding new images to a bundle.

**Comment by Lin87** [comment]
Not a bug. It is working as intended but I'll enhance it to allow multiple selections and update the frame table accordingly.

**Comment by Lin87** [comment]
The add frame ➕button can now select multiple images. To be released in build 24.
