### ISSUE TITLE
Program Crashes. Can't open at all.

### ISSUE THREAD

**Issue by n-meyer** [oel-mediateam/storybook-packager-public#3]
I haven't been able to get the application to open yet. I seem to be stuck in a loop where it will say that it quit unexpectedly. I'll click don't reopen, and then when I try to create a new project it crashes and I get an error report. I've tried deleting app, re-starting computer, reinstalling and that did not fix it either.

![Screen Shot 2019-04-18 at 3 44 42 PM](https://user-images.githubusercontent.com/49766744/56390126-e693c500-61f0-11e9-845b-8bdb107cb3b1.png)
![Screen Shot 2019-04-18 at 3 41 21 PM](https://user-images.githubusercontent.com/49766744/56390132-e8f61f00-61f0-11e9-85e2-1c5f47bc23cd.png)

**Comment by Lin87** [comment]
The issue is resolved. The error was caused by not finding value in app preferences.
