### ISSUE TITLE
Duplicating packager project mp3 download issue

### ISSUE THREAD

**Issue by n-meyer** [oel-mediateam/storybook-packager-public#30]
In my process for storybook creation I duplicate my .sbproj project as I move from lesson to lesson in a course so I don't have to refill information that is consistent across the course. When I duplicate a .sbproj file though it clears the downloadable .mp3 from view in the storybook packager, but when I go show package contents the file is still there
![Screen Shot 2019-08-15 at 10 40 01 AM](https://user-images.githubusercontent.com/49766744/63106940-8e27c680-bf49-11e9-90e6-5aab4c83efb9.png)

**Comment by owlboy** [comment]
It was noted in a meeting that this happens with Transcripts too.

**Comment by Lin87** [comment]
Fixed. Will be in next updated release (Build 27)
