### ISSUE TITLE
Quiz images not working

### ISSUE THREAD

**Issue by n-meyer** [oel-mediateam/storybook-packager-public#31]
I can't seem to add images to quiz questions. Dragging and dropping doesn't work and when I click on the image preview icon nothing happens. I tried changing the XML file manually, but then when I open up the packager and try to click on the quiz it crashes.

**Comment by Lin87** [comment]
Adding image to quiz is not supported yet. What you see there is just placeholders. Next updates will add quiz images supports

**Comment by Lin87** [comment]
Closing this since this is a duplicate and on a feature that has not been released yet.
