### ISSUE TITLE
[Crash] Adding a new page while editing a page title causes a crash.

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/storybook-packager-public#46]
**Steps to reproduce:**
1. Enter new text in a Page Title
2. Do not change the focus from the text field.
3. Click the `+ Page` button.
-- Crash--

**Recording:**
https://drive.google.com/file/d/17HGIklq1XI1uU6o3xHFpY8gOQCqqxIaP/view?usp=sharing

**Crash Log info:**
```
Application Specific Information:
Performing @selector(titleEndEditing:) from sender NSTextField 0x7fb8f0c3b4d0
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/ethan.lin/Desktop/GitHub/storybook-packager/StorybookPackager/StorybookPackager/PageViews/PageViewController.swift, line 325
```
It looks like hardcoded references again.

**Comment by Lin87** [comment]
Fixed. Will be in next update release...
