### ISSUE TITLE
Updating a bundle image does not refresh the preview

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/storybook-packager-public#8]
When updating individual frames in a bundle, the preview does not update.
Tested with SVG images.

**Comment by Lin87** [comment]
Hi @owlboy Sorry for the delay. It has been a while and I am not sure if you can recall, but could you provide more information? The frame does not update when you updated the frame time or the image?

**Comment by Lin87** [comment]
Oops, can't read. Please ignore previous comment and question.

**Comment by Lin87** [comment]
Fixed build 23.
